### PR TITLE
Add no_std support

### PR DESCRIPTION
**Pull request by C0D3-M4513R**
(cherry picked from commit 191d4f480c73addc3966be1631955c4a0362647f)

### Summary of the PR

*Please summarize here why the changes in this PR are needed.*

It makes this crate actually usable in no_std environments.

### Requirements

Before submitting your PR, please make sure you addressed the following
requirements:

- [x] All commits in this PR are signed (with `git commit -s`), and the commit
  message has max 60 characters for the summary and max 75 characters for each
  description line.
- [ ] All added/changed functionality has a corresponding unit/integration
  test.
- [ ] All added/changed public-facing functionality has entries in the "Upcoming 
  Release" section of CHANGELOG.md (if no such section exists, please create one).
- [x] Any newly added `unsafe` code is properly documented.

### CODE REVIEW

**Comment by C0D3-M4513R** [comment]
Refusing to touch the Changelog, since:
> You don't need to edit the changelog it is automatically generated from commit messages.

**Review by JonathanWoollett-Light — CHANGES_REQUESTED** [review]
Could you please remove the commit message line 

> (cherry picked from commit https://github.com/JonathanWoollett-Light/ux2/commit/191d4f480c73addc3966be1631955c4a0362647f)

from the commit.

**Comment by C0D3-M4513R** [comment]
Done

**Review by JonathanWoollett-Light — APPROVED** [review]
lgtm

**Pull request merged**
